config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#home"

  resources :bikes, except: [:show, :destroy] do
    get 'search' => 'bikes#search', on: :collection
    get 'print_select' => 'bikes#print_select', on: :collection
    get 'print_labels' => 'bikes#print_labels', on: :collection
    get 'freecyclery_pickup' => 'bikes#freecyclery_pickup', on: :collection
    patch 'mark_as_sold' => 'bikes#mark_as_sold', on: :member
  end

  resources :volunteers
  resources :agencies
  resources :clients do
    get 'receipt' => 'freecyclery#receipt'
    get 'print_select' => 'clients#print_select', on: :collection
    get 'print_receipts' => 'clients#print_receipts', on: :collection
  end

  get 'bikes_by_location' => 'static_pages#bikes_by_location'
  get 'sale_bikes' => 'static_pages#sale_bikes'
  get 'closed_applications' => 'freecyclery#closed_applications'
  get 'voided_applications' => 'freecyclery#voided_applications'
  get 'available_bikes' => 'freecyclery#available_bikes'
  get 'bikes_sold_per_year' => 'reports#bikes_sold_per_year'
  get 'bikes_fixed_per_week' => 'reports#bikes_fixed_per_week'
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index 
    @volunteers = Volunteer.all
  end

  def show; end

  def new
    @volunteer = Volunteer.new
  end

  def edit; end
 
  def create
    @volunteer = Volunteer.new(volunteer_params)
    if @volunteer.save
      redirect_to @volunteer, notice: 'Volunteer was successfully created.'
    else
      render action: 'new' 
    end
  end

  def update
    if @volunteer.update(volunteer_params)
      redirect_to @volunteer, notice: 'Volunteer was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @volunteer.destroy
    redirect_to volunteers_url
  end



  private
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    def volunteer_params
      params.require(:volunteer).permit(:name, :email, :phone) 
    end
end

app/views/volunteers/_fields.html.haml
- disabled ||= false

.form-group
  = f.label "Name", class: "col-sm-2 control-label"
  .col-sm-10
    = f.text_field :name, class: "form-control", disabled: disabled

.form-group
  = f.label "Email address:", class: "col-sm-2 control-label"
  .col-sm-10
    = f.text_field :email, class: "form-control", disabled: disabled

.form-group
  = f.label "Phone Number:", class: "col-sm-2 control-label"
  .col-sm-10
    = f.text_field :phone, class: "form-control", disabled: disabled

app/views/volunteers/_form.html.haml
.container
  = form_for @volunteer, html: {class: 'form-horizontal'} do |f|
    - if @volunteer.errors.any?
      #error_explanation
        %h2= pluralize(@volunteer.errors.count, "error") + "prohibited this volunteer from being saved:"
        %ul
        - @volunteer.errors.full_messages.each do |msg|
          %li= msg
    = render 'fields', f: f
    .row
      .actions.col-sm-offset-2
        = f.submit class: "btn btn-default"

app/views/volunteers/edit.html.haml
.container
  %h1 Editing Volunteer Information
  = render 'form'
  = link_to 'Show', @volunteer
  |
  = link_to 'Back', volunteers_path

app/views/volunteers/index.html.haml
.container
  %h1 Volunteers
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Phone
        %th Email
        %th
        %th
        %th
    %tbody
      - @volunteers.each do |volunteer|
        %tr
          %td= volunteer.name
          %td= volunteer.phone
          %td= volunteer.email
          %td= link_to 'Show', volunteer
          %td= link_to 'Edit', edit_volunteer_path(volunteer)
          %td= link_to 'Destroy', volunteer, method: :delete, data: { confirm: 'Are you sure?' }

  = link_to '+ Add Volunteer', new_volunteer_path, class: "btn btn-default"

app/views/volunteers/new.html.haml
%h1 New Volunteer
= render 'form'
= link_to 'Back', volunteers_path

app/views/volunteers/show.html.haml
.container
  %p#notice= notice
  = form_for(@volunteer) do |f|
    = render 'fields', f: f, disabled: true
  = link_to 'Edit', edit_volunteer_path(@volunteer)
  |
  = link_to 'Back', volunteers_path