config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#home"

  resources :bikes, except: [:show, :destroy] do
    get 'search' => 'bikes#search', on: :collection
    get 'print_select' => 'bikes#print_select', on: :collection
    get 'print_labels' => 'bikes#print_labels', on: :collection
    get 'freecyclery_pickup' => 'bikes#freecyclery_pickup', on: :collection
    patch 'mark_as_sold' => 'bikes#mark_as_sold', on: :member
  end

  resources :volunteers
  resources :agencies
  resources :clients do
    get 'receipt' => 'freecyclery#receipt'
    get 'print_select' => 'clients#print_select', on: :collection
    get 'print_receipts' => 'clients#print_receipts', on: :collection
  end

  get 'bikes_by_location' => 'static_pages#bikes_by_location'
  get 'sale_bikes' => 'static_pages#sale_bikes'
  get 'closed_applications' => 'freecyclery#closed_applications'
  get 'voided_applications' => 'freecyclery#voided_applications'
  get 'available_bikes' => 'freecyclery#available_bikes'
  get 'bikes_sold_per_year' => 'reports#bikes_sold_per_year'
  get 'bikes_fixed_per_week' => 'reports#bikes_fixed_per_week'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def home; end

  def bikes_by_location
    @sales_floor_bikes = Bike.where(location: Bike::SALES_FLOOR, purpose: Bike::SALE, date_sold: nil)
    @paulina_basement_bikes = Bike.where(location: Bike::PAULINA_BASEMENT, purpose: Bike::SALE, date_sold: nil)
    @seward_basement_bikes = Bike.where(location: Bike::SEWARD_BASEMENT, purpose: Bike::SALE, date_sold: nil)
  end

  def sale_bikes
    @sale_bikes = Bike.where(purpose: Bike::SALE, date_sold: nil)
    respond_to do |format|
      format.html
      format.csv { send_data @sale_bikes.to_csv_for_reconciliation, filename: "sale_bikes-#{Date.today}.csv" }
    end
  end
end

app/views/static_pages/bikes_by_location.html.haml
.container
  %p (These lists exclude freecyclery bikes and sold bikes.)

  %h1 Sales Floor:
  %ul
    - @sales_floor_bikes.each do |bike|
      %li= bike.name

  %h1 Paulina basement:
  %ul
    - @paulina_basement_bikes.each do |bike|
      %li= bike.name

  %h1 Seward Basement:
  %ul
    - @seward_basement_bikes.each do |bike|
      %li= bike.name

app/views/static_pages/home.html.haml
.container
  %h1 Bikes n' Clients
  %br
  %h2 Bikes
  %br
  = link_to "Log Bikes", new_bike_path
  %br
  = link_to "View Bikes", bikes_path
  %br
  = link_to "View Bikes by Location", bikes_by_location_path
  %br
  = link_to "Print Sale Labels", print_select_bikes_path
  %br
  = link_to "List All Sale Bikes", sale_bikes_path
  %br
  = link_to "Download CSV of Sale Bikes (for reconciliation)", sale_bikes_path(format: "csv")
  %br
  = link_to "Export Bikes to CSV", bikes_path(format: "csv")
  %br
  %h2 Freecyclery
  %br
  = link_to "Add Freecyclery Clients", new_client_path
  %br
  = link_to "Freecyclery Clients", clients_path
  %br
  = link_to "Freecyclery Agencies", agencies_path
  %br
  = link_to "Print Client Receipts", print_select_clients_path
  %br
  = link_to "Freecyclery Closed Applications", closed_applications_path
  %br
  = link_to "Freecyclery Voided Applications", voided_applications_path
  %br
  = link_to "Available Bikes", available_bikes_path
  %h2 Reports
  %br
  = link_to "Bikes Sold Per Year", bikes_sold_per_year_path
  %br
  = link_to "Bikes Fixed Per Week", bikes_fixed_per_week_path

app/views/static_pages/sale_bikes.html.haml
.container
  %h1 All Bikes We Have For Sale:
  %ul
    - @sale_bikes.each do |bike|
      %li= link_to(bike.name, edit_bike_path(bike))