config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#home"

  resources :bikes, except: [:show, :destroy] do
    get 'search' => 'bikes#search', on: :collection
    get 'print_select' => 'bikes#print_select', on: :collection
    get 'print_labels' => 'bikes#print_labels', on: :collection
    get 'freecyclery_pickup' => 'bikes#freecyclery_pickup', on: :collection
    patch 'mark_as_sold' => 'bikes#mark_as_sold', on: :member
  end

  resources :volunteers
  resources :agencies
  resources :clients do
    get 'receipt' => 'freecyclery#receipt'
    get 'print_select' => 'clients#print_select', on: :collection
    get 'print_receipts' => 'clients#print_receipts', on: :collection
  end

  get 'bikes_by_location' => 'static_pages#bikes_by_location'
  get 'sale_bikes' => 'static_pages#sale_bikes'
  get 'closed_applications' => 'freecyclery#closed_applications'
  get 'voided_applications' => 'freecyclery#voided_applications'
  get 'available_bikes' => 'freecyclery#available_bikes'
  get 'bikes_sold_per_year' => 'reports#bikes_sold_per_year'
  get 'bikes_fixed_per_week' => 'reports#bikes_fixed_per_week'
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :bike, optional: true
  belongs_to :agency

  before_update :stamp_assigned_date, if: proc { !bike_id_was && bike_id_changed? }

  def self.waiting_list
    clients = Client.all
    nonvoided_clients = clients.select{|client| !client.application_voided}
    active_nonvoided_clients = nonvoided_clients.select{|client| !client.pickup_date}
    waiting_list = active_nonvoided_clients.select{|client| !client.application_date.nil?}
    waiting_list.sort_by!{|client| client.application_date}
  end

  def name
    self.first_name + ' ' + self.last_name
  end

  def self.closed_applications
    Client.all.order(pickup_date: :desc).select{|client| client.pickup_date}
  end

  def self.voided_applications
    Client.all.where(application_voided: true)
  end

  private

  def stamp_assigned_date
    self.assigned_bike_at = Time.zone.now
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update]
  before_action :authenticate_user!

  def index
    @waiting_list = Client.waiting_list
    @clients = Client.all.reverse_order
  end

  def new
    @client = Client.new
  end

  def edit; end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to new_client_path, notice: 'Client was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @client.update(client_params)
    if @client.save
      redirect_to edit_client_url(@client), notice: "Client was successfully updated"
    else
      render action: 'edit', notice: "Unable to update client"
    end
  end

  def print_select
    @clients = Client.includes(:bike, :agency)
                     .where.not(bike_id: nil)
                     .where.not(agency_id: nil)
                     .order('assigned_bike_at DESC NULLS LAST')
                     .page(params[:page]).per(30)
  end

  def print_receipts
    client_ids = print_params.to_unsafe_hash.map{|key, value| key if value == "1"}.compact
    @clients = Client.find(client_ids)
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(
        :first_name,
        :last_name,
        :application_date,
        :gender,
        :age,
        :height,
        :weight,
        :helmet,
        :lock,
        :bike_id,
        :will_pay,
        :bike_type_requested,
        :agency_id,
        :notes,
        :bike_fixed,
        :application_voided,
        :pickup_date,
        :volunteer_at_pickup)
    end

    def print_params
      params.require(:print_clients)
    end
end

app/views/clients/_edit_form.html.haml
= form_with model: @client, html: {class: 'form-horizontal'} do |f|
  - if @client.errors.any?
    #error_explanation
      %h2= pluralize(@client.errors.count, "error") + " prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg
  = render 'fields', f: f
  .row
    .actions.col-sm-offset-2
      = f.submit "Save Changes", class: "btn btn-default btn-outline-dark"

app/views/clients/_fields.html.haml
- disabled ||= false
.col-sm-8.offset-md-2
  .form-group.row
    = f.label "First Name", class: "col-sm-2 col-form-label"
    .col-sm-10= f.text_field :first_name, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Last Name", class: "col-sm-2 col-form-label"
    .col-sm-10= f.text_field :last_name, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Gender", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :gender, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Weight (lb)", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :weight, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Age", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :age, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Height (ft)", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :height, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Application Date:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.date_field :application_date, value: @client.application_date && @client.application_date.strftime("%Y-%m-%d"), class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Agency:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.select :agency_id, Agency.order(:name).collect {|b| [ b.name, b.id ] }, {include_blank: 'None'}, class: "form-select", disabled: disabled
  .form-group.row
    = f.label "Type of Bike Requested:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.select :bike_type_requested, Bike::BIKE_TYPES.map{|t| [t, t]}, {include_blank: "No Preference"}, class: "form-select", disabled: disabled
  .form-group.row
    = f.label "Will Pay 25$ for Lock & Helmet:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.check_box :will_pay, disabled: disabled
  .form-group.row
    = f.label "Helmet", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.check_box :helmet, disabled: disabled
  .form-group.row
    = f.label "Lock", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.check_box :lock, disabled: disabled
  .form-group.row
    = f.label "Bike:", class: "col-sm-2 col-form-label"
    .col-sm-10
      - if @client.bike_id
        = f.select :bike_id, options_for_select( Bike.available_for_freecyclery.collect{|b| [ b.name, b.id ]} + [[@client.bike.name, @client.bike_id]], @client.bike_id ), {include_blank: 'None'}, class: "form-select", disabled: disabled
      - else
        = f.select :bike_id, options_for_select( Bike.available_for_freecyclery.collect{|b| [ b.name, b.id ]}, @client.bike_id ), {include_blank: 'None'}, class: "form-select", disabled: disabled
  .form-group.row
    = f.label "Notes:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_area :notes, class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Bike Fixed:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.check_box :bike_fixed, disabled: disabled
  .form-group.row
    = f.label "Bike Assigned On:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :assigned_bike_at, value: @client.assigned_bike_at && @client.assigned_bike_at.strftime('%m/%d/%Y') || "N/A", disabled: true
  .form-group.row
    = f.label "Bike Picked Up On:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.date_field :pickup_date, value: @client.pickup_date && @client.pickup_date.strftime('%Y-%m-%d'), class: "form-control", disabled: disabled
  .form-group.row
    = f.label "Volunteer Present at Pickup:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :volunteer_at_pickup, class: "form-control", disabled: disabled
  %br
  .form-group.row
    .col-sm-8
    = f.label "Application Voided:", class: "float-right col-sm-2 col-form-label"
    .col-sm-2
      = f.check_box :application_voided, disabled: disabled

app/views/clients/_new_form.html.haml
= form_with model: @client, html: {class: 'form-horizontal'} do |f|
  - if @client.errors.any?
    #error_explanation
      %h2= pluralize(@client.errors.count, "error") + " prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg
  = render 'fields', f: f
  .row
    .actions.col-sm-offset-2
      = f.submit "Save And Add Another", class: "btn btn-outline-dark"

app/views/clients/_receipt.html.haml
.col-6
  .receipt
    %h2= client.bike.name
    %br
      .horizontal-line
      .client-information
        %strong= "#{client.name}#{" - " + client.agency.name if client.agency}"
      .horizontal-line
      .receipt-body
        %p= "Includes Helmet" if client.helmet
        %p= "Includes Lock" if client.lock
        %p= "Owes $25" if client.will_pay
        %br
        %p Date ___________________
        %br
        %br
        _______________________________________
        %br
        Client Signature
        %br
        %br
        %br
        ____________   Recyclery Initials

.col-6
  .receipt
    %h2= client.bike.name
    %br
      .horizontal-line
      .client-information
        %strong= "#{client.name}#{" - " + client.agency.name if client.agency}"
      .horizontal-line
      .receipt-body
        %p= "Includes Helmet" if client.helmet
        %p= "Includes Lock" if client.lock
        %p= "Owes $25" if client.will_pay
        %br
        %p Date ___________________
        %br
        %br
        ______________________________________
        %br
        Client Signature
        %br
        %br
        ____________ Recyclery Initials
        %br
        %br
        %br
        _______________________________________
        %br
        Contact Email
        %br
        %br
        _________________________________ Contact Phone
        %br
        %br
        &#9634; Client grants The Recyclery Collective consent to use and publish photos.

app/views/clients/_receipt_button.html.haml
.btn.btn-default
  = link_to 'Print Receipt', client_receipt_path(@client)

app/views/clients/edit.html.haml
.container
  %h1 Edit client
  = render 'receipt_button' if @client.bike_id
  = render 'edit_form'
  = link_to 'Back', clients_path

app/views/clients/index.html.haml
.container
  .row
    = link_to ' + New Client', new_client_path, class: "btn btn-lg btn-outline-dark"
  .row
    %h1 Client Waiting List
    %p The waiting list shows clients who have not been voided or picked up their bike. Only clients with an application date are shown.

    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Number
          %th First Name
          %th Last Name
          %th Height
          %th Application Date
          %th Agency
          %th Type Requested
          %th Bike
          %th
      %tbody
        - @waiting_list.each_with_index do |client, index|
          %tr
            %td= index + 1
            %td= client.first_name
            %td= client.last_name
            %td= client.height
            %td= client.application_date
            %td= client.agency.name if client.agency
            %td= client.bike_type_requested
            %td= client.bike_id ? Bike.find(client.bike_id).name : "None"
            %td= link_to 'Edit', edit_client_path(client)

    %br
  .row
    %h1 All Clients

    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th First Name
          %th Last Name
          %th Agency
          %th
      %tbody
        - @clients.each do |client|
          %tr
            %td= client.first_name
            %td= client.last_name
            %td= client.agency.name if client.agency
            %td= link_to 'Edit', edit_client_path(client)

    %br

app/views/clients/new.html.haml
.container-fluid
  %h1 New Client
  = render 'new_form'
  = link_to 'Back', clients_path

app/views/clients/print_receipts.html.haml
.container-fluid.print-receipts
  - @clients.each do |client|
    .row.gx-10
      = render partial: "receipt", locals: {client: client}

app/views/clients/print_select.html.haml
.container
  %h1 Select the clients whose receipts you would like to print
  %p Only clients with a bike and an agency assigned are shown on this page.

  =form_tag("/clients/print_receipts", method: "get") do
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Client
          %th Bike
          %th Select
        -@clients.each do |client|
          %tr
            %td= client.name
            %td= client.bike ? client.bike.name : ""
            %td= check_box("print_clients", client.id)
    =paginate @clients
    %br
    =submit_tag 'Generate Receipts', class: "btn btn-default"