config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#home"

  resources :bikes, except: [:show, :destroy] do
    get 'search' => 'bikes#search', on: :collection
    get 'print_select' => 'bikes#print_select', on: :collection
    get 'print_labels' => 'bikes#print_labels', on: :collection
    get 'freecyclery_pickup' => 'bikes#freecyclery_pickup', on: :collection
    patch 'mark_as_sold' => 'bikes#mark_as_sold', on: :member
  end

  resources :volunteers
  resources :agencies
  resources :clients do
    get 'receipt' => 'freecyclery#receipt'
    get 'print_select' => 'clients#print_select', on: :collection
    get 'print_receipts' => 'clients#print_receipts', on: :collection
  end

  get 'bikes_by_location' => 'static_pages#bikes_by_location'
  get 'sale_bikes' => 'static_pages#sale_bikes'
  get 'closed_applications' => 'freecyclery#closed_applications'
  get 'voided_applications' => 'freecyclery#voided_applications'
  get 'available_bikes' => 'freecyclery#available_bikes'
  get 'bikes_sold_per_year' => 'reports#bikes_sold_per_year'
  get 'bikes_fixed_per_week' => 'reports#bikes_fixed_per_week'
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :clients
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @agencies = Agency.all
  end

  def show
  end

  def new
    @agency = Agency.new
  end

  def edit
  end

  def create
    @agency = Agency.new(agency_params)
    if @agency.save
      redirect_to @agency, notice: 'Agency was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @agency.update(agency_params)
      redirect_to @agency, notice: 'Agency was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @agency.destroy
    redirect_to clients_url
  end

  private
    def set_agency
      @agency = Agency.find(params[:id])
    end

    def agency_params
      params.require(:agency).permit(
        :name,
        :contact_name,
        :street_address,
        :city,
        :state,
        :postal_code,
        :phone,
        :email)
    end
end

app/views/agencies/_fields.html.haml
- disabled ||= false
.form-horizontal
  .form-group.row
    = f.label "Name of Agency:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "Contact Name:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :contact_name, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "Street Address:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :street_address, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "City:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :city, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "State:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :state, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "Postal Code:", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :postal_code, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "Phone Number", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :phone, class: "form-control", disabled: disabled

  .form-group.row
    = f.label "email", class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_field :email, class: "form-control", disabled: disabled

app/views/agencies/_form.html.haml
= form_for @agency, html: {class: 'form-horizontal'} do |f|
  - if @agency.errors.any?
    #error_explanation
      %h2= pluralize(@agency.errors.count, "error") + " prohibited this agency from being saved:"
      %ul
        - @agency.errors.full_messages.each do |msg|
          %li= msg
  = render 'fields', f: f
  .row
    .actions.col-sm-offset-2
      = f.submit class: "btn btn-outline-dark"

app/views/agencies/edit.html.haml
.container
  %h1 Edit Agency
  = render 'form'
  = link_to 'Show', @agency
  |
  = link_to 'Back', agencies_path

app/views/agencies/index.html.haml
.container
  %h1 Agencies

  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Agency
        %th
        %th
        %th
    %tbody
      - @agencies.each do |agency|
        %tr
          %td= agency.name
          %td= link_to 'Show', agency
          %td= link_to 'Edit', edit_agency_path(agency)
          %td= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' }

  %br
  = link_to ' + New Agency', new_agency_path, class: "btn btn-outline-dark"

app/views/agencies/new.html.haml
.container
  %h1 New Agency
  = render 'form'
  = link_to 'Back', agencies_path

app/views/agencies/show.html.haml
.container
  %p#notice= notice
  = form_for(@agency) do |f|
    = render 'fields', f: f, disabled: true
  = link_to 'Edit', edit_agency_path(@agency)
  |
  = link_to 'Back', agencies_path